apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-resource-limit
spec:
  steps:
    - name: consume-cpu
      image: ubuntu
      command:
        - bash
        - -c
      args:
        - i=0;
        - while true; do i=i+1; done
    - name: sleep
      image: ubuntu
      command:
        - sleep 300
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: resource-limit-
spec:
  taskRef:
    name: task-resource-limit
  computeResources:
    requests:
      cpu: 0.1
    limits:
      cpu: 0.3
