apiVersion: v1
kind: Endpoints
metadata:
  name: harbor-external
subsets:
  - addresses:
      - ip: 192.168.110.72
    ports:
      - name: "harbor-external-port"
        port: 443
        protocol: TCP