apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-external
subsets:
  - addresses:
      - ip: 192.168.110.125
    ports:
      - name: "mysql-external-port"
        port: 3306
        protocol: TCP