apiVersion: v1
kind: Endpoints
metadata:
  name: redis-external
subsets:
  - addresses:
      - ip: 192.168.110.125
    ports:
      - name: "redis-external-port"
        port: 6379
        protocol: TCP