kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  nacos-pvc
  namespace: devops #非业务类统一资源对象统一放在 devops命名空间下
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: localstore01 
