apiVersion: v1
kind: Service
metadata: 
  labels:
    run: nginx-clusterip
  name: nginx-clusterip
  namespace: default
spec:
  ports: 
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
  selector:
    run: nginx-clusterip


