apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: step-demo-script
spec:
  steps:
    - name: hello
      image: ubuntu
      command:
        - echo
      args:
        - "Hello $(params.username)!"

    - name: bash # Running bash within Steps
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "Hello from Bash!"

  params:
    - name: username
      type: string
