apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: step-demo-onerror
spec:
  steps:
    - image: docker.io/library/golang:latest
      name: ignore-unit-test-failure
      onError: continue #
      script: |
        go test .
    - name: bash # Running bash within Steps
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "Hello from Bash!"
