apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv1
spec:
  capacity:
    storage: 1Gi  #pv的存储空间容量
  accessModes: ["ReadWriteOnce"]
  nfs:
    path: /glzt/nfs-data/pv1 #把nfs的存储空间创建成pv
    server: 192.168.110.72     #nfs服务器的地址
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv2
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteMany"]
  nfs:
    path: /glzt/nfs-data/pv2
    server: 192.168.110.72
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv3
spec:
  capacity:
    storage: 3Gi
  accessModes: ["ReadOnlyMany"]
  nfs:
    path: /glzt/nfs-data/pv3
    server: 192.168.110.72
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv4
spec:
  capacity:
    storage: 4Gi
  accessModes: ["ReadWriteOnce","ReadWriteMany"]
  nfs:
    path: /glzt/nfs-data/pv4
    server: 192.168.110.72
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv5
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteOnce","ReadWriteMany"]
  nfs:
    path: /glzt/nfs-data/pv5
    server: 192.168.110.72
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv6
spec:
  capacity:
    storage: 6Gi
  accessModes: ["ReadWriteOnce","ReadWriteMany"]
  nfs:
    path: /glzt/nfs-data/pv6
    server: 192.168.110.72
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv7
spec:
  capacity:
    storage: 7Gi
  accessModes: ["ReadWriteOnce","ReadWriteMany"]
  nfs:
    path: /glzt/nfs-data/pv7
    server: 192.168.110.72
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv8
spec:
  capacity:
    storage: 8Gi
  accessModes: ["ReadWriteOnce","ReadWriteMany"]
  nfs:
    path: /glzt/nfs-data/pv8
    server: 192.168.110.72
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv9
spec:
  capacity:
    storage: 9Gi
  accessModes: ["ReadWriteOnce","ReadWriteMany"]
  nfs:
    path: /glzt/nfs-data/pv9
    server: 192.168.110.72

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv10
spec:
  capacity:     
    storage: 10Gi
  accessModes: ["ReadWriteOnce","ReadWriteMany"]
  nfs:
    path: /glzt/nfs-data/pv10  
    server: 192.168.110.72
