apiVersion: v1
kind: Pod
metadata:
  name: nginx-emptydir
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
    ports:
    - name: http
      containerPort: 80
  volumes:
  - name: html
    emptyDir: {}
