apiVersion: v1
kind: Pod
metadata:
 name: nginx-nfs
spec:
 containers:
 - name: nginx
   image: nginx
   imagePullPolicy: IfNotPresent
   ports:
   - containerPort: 80
     protocol: TCP
   volumeMounts:
   - name: nginx-nfs
     mountPath: /usr/share/nginx/html
 volumes:
 - name: nginx-nfs
   nfs:
    path: /glzt/nfs-data
    server: 192.168.110.72
