apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: fluentd-efk
  namespace: default
  labels:
    project: monitor-efk
    app: fluentd-efk
spec: 
  minReadySeconds: 10
  revisionHistoryLimit: 5
  selector: 
    matchLabels:
      app: fluentd-efk
      project: monitor-efk
  template: 
    metadata:
      name: fluentd-efk
      namespace: default
      labels:
        project: monitor-efk
        app: fluentd-efk
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: xianchao/fluentd:v2.5.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts: 
        - name: hostlogs
          mountPath: /var/log
        - name: containerlogs
          mountPath: /var/lib/docker/containers
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hostlogs
        hostPath: 
          path: /var/log
      - name: containerlogs
        hostPath:
          path: /var/lib/docker/containers
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10
