apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volume-mysql
      mountPath: /etc/secret
      readOnly: true
  volumes:
  - name: volume-mysql
    secret:
      secretName: secret-mysql
