apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
spec:
  externalTrafficPolicy: Local
  selector:
    app: kubia
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
