apiVersion: v1
kind: Service
metadata:
  name: mysql-manage
  labels:
    name: mysql-manage
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31255
      name: "mysql-manage-port"
  selector:
    app: mysql