kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: devops
  labels:
    app: postgres
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi