apiVersion: scheduling.kubefed.io/v1alpha1
kind: ReplicaSchedulingPreference
metadata:
  name: httpserver
spec:
  targetKind: FederatedDeployment
  totalReplicas: 3
  clusters:
    gke-asia-01:
      minReplicas: 1
      maxReplicas: 1
      weight: 1