apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limits
  namespace: production
spec:
  limits:
  - type: Pod # 指定整个Pod的limits和requests
    min: # Pod中所有容器CPU和Memory资源的最小值
      cpu: 100m
      memory: 10Mi
    max: # Pod中所有容器CPU和Memory资源的最大值
      cpu: 1
      memory: 1Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: production
spec:
  limits:
  - type: Container # 指定容器的limits和requests
    defaultRequest: # 资源清单中没有指定requests时，requests的默认值
      cpu: 100m
      memory: 32Mi
    default: # 资源清单中没有指定limits时，limits的默认值
      cpu: 500m
      memory: 512Mi
    min: # 容器CPU和Memory资源的最小值
      cpu: 50m
      memory: 8Mi
    max: # 容器CPU和Memory资源的最大值
      cpu: 1
      memory: 1Gi
    maxLimitRequestRatio: # 容器中limits和requests最大比例
      cpu: 4
      memory: 10
