apiVersion: v1
kind: Pod
metadata:
  name: pod-podantiaffanity-1
  labels:
    app: lymphoma
    tier: frontend
spec:
  containers:
  - name: lym-web
    image: ikubernetes/myapp:v1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-podantiaffanity-2
  labels:
    app: lymphoma
    tier: backend
spec:
    containers:
    - name: lym-django
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command: ["sh","-c","sleep 3600"]
    affinity:
      podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
         - labelSelector:
             matchExpressions:
             - {key: tier, operator: In, values: ["frontend"]}
           topologyKey: kubernetes.io/hostname

