apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: yapi-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs # 根据实际使用的存储来定
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: yapi-system
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: yapi-mongo
          image: goharbor.com/devops/mongo:4 # 内部harbor仓库
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 100Mi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: mongo-port
          volumeMounts:
            - name: mongo-data
              mountPath: /var/lib/mongo
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: yapi-system
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: "mongo"
  selector:
    app: mongo
