kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube
  namespace: devops
  labels:
    app: sonarqube
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi