apiVersion: v1
kind: Pod
metadata:
  name: initial-delay
spec:
  containers:
    - name: initial-delay
      image: busybox
      args:
        - /bin/sh
        - -c
        # - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
        # readinessProbe and livenessProbe will execute AFTER startup
        - sleep 600
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 30
        periodSeconds: 5