apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe
spec:
  containers:
    - name: readiness-probe
      image: busybox
      args:
        - /bin/sh
        - -c
        - sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 10
        periodSeconds: 5