apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: run-with-parameters
spec:
  taskRef:
    name: task-with-parameters
  params:
    - name: git-url
      value: "https://github.com/cncamp/golang.git"
    - name: commit-id
      value: "dadasdad"
    - name: "foo.bar"
      value: "https://www.google.com"
