apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-with-params
spec:
  params:
    - name: git-url
      type: string
    - name: commit-id
      type: string
  results:
    - name: echo-output
      description: "successful echo"
  steps:
    - name: echo
      image: ubuntu
      command:
        - "echo"
      args:
        - "$(params.git-url)"
        - "-"
        - "$(params.commit-id)"
    - name: sleep
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        sleep 600
