apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-with-params
spec:
  taskRef:
    name: task-with-parameters
  params:
    - name: git-url
      value: "https://github.com/cncamp/golang.git"
    - name: commit-id
      value: "dadasdad"
