apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-with-parameters
spec:
  params:
    - name: git-url
      type: string
    - name: commit-id
      type: string
    - name: foo.bar
      description: "the name contains dot character"
      default: "test"
  results:
    - name: echo-output
      description: "successful echo"
  steps:
    - name: clone
      image: bitnami/git:2.37.1
      args:
        - "-url=$(params.url)"
        - "-revision=$(params.commit)"
    - name: sleep
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        sleep 600
