apiVersion: v1
kind: Pod
metadata:
  name: mysql-keyref
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    env:
    - name: MYSQL_ROOT_PASSWORD # 它是Pod启动成功后,Pod中容器的环境变量名.
      valueFrom:
        secretKeyRef:
          name: secret-mysql # 这是secret的对象名
          key: mysql_passwd # 它是secret中的key名
