apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nacos
      app: nacos
  template:
    metadata:
      labels:
        service: nacos
        app: nacos
    spec:
      containers:
      #nacos
      - image: nacos/nacos-server:latest
        imagePullPolicy: IfNotPresent
        name: nacos-server
        env:
        - name: "PREFER_HOST_MODE"
          value: "hostname"
        - name: "MODE"
          value: "standalone"
        - name: "SPRING_DATASOURCE_PLATFORM"
          value: "mysql"
        - name: "MYSQL_SERVICE_HOST"
          value: "mysql"
        - name: "MYSQL_SERVICE_DB_NAME"
          value: "nacos"
        - name: "MYSQL_SERVICE_PORT"
          value: "3306"
        - name: "MYSQL_SERVICE_USER"
          value: "root"
        - name: "MYSQL_SERVICE_PASSWORD"
          value: "nacos123"
        ports:
        - containerPort: 8848
          name: "nacos-port"
        volumeMounts:
        - mountPath: /home/nacos/logs
          name: nacos-pv
          subPath: logs
        - name: nacos-config
          mountPath: /home/nacos/init.d/custom.properties
          subPath: custom.properties
        - mountPath: /etc/localtime
          name: nacos-time
        startupProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          tcpSocket:
            host: mysql
            port: 3306
      volumes:
      - name: nacos-pv
        persistentVolumeClaim:
          claimName: nacos-pvc
      - name: nacos-config
        configMap:
          name: custom.properties
      - name: nacos-time
        hostPath:
          path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: default
spec:
  ports:
    - port: 8848
      targetPort: 8848
      name: "nacos-port"
  selector:
    app: nacos