apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: github-build
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
      default: cncamp/httpserver:v1.0
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./httpserver/Dockerfile
  steps:
    - name: github-build
      image: cncamp/executor
      workingDir: /workspace/source
      args:
        - "--dockerfile=./httpserver/Dockerfile"
        - "--context=./httpserver"
        - "--destination=cncamp/httpserver:20220805"
  workspaces:
    - name: dockerconfig
      description: Includes a docker `config.json`
      optional: true
      mountPath: /kaniko/.docker
    - name: source
      description: source code storage
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: github-build
spec:
  serviceAccountName: cncamp-sa
  taskRef:
    name: github-build
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: storage-code
    - name: dockerconfig
      secret:
        secretName: docker-auth
