apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: github-build
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
      default: goharbor.com/mall-swarm/mall-admin:latest
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./mall-admin/Dockerfile
  steps:
    - name: sleep
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        sleep 600
    - name: github-build
      image: cncamp/executor
      workingDir: /workspace/source
      args:
        - "--dockerfile=./mall-admin/Dockerfile"
        - "--context=/workspace/source"
        - "--destination=goharbor.com/mall-swarm/mall-admin:latest"
  workspaces:
    - name: dockerconfig
      description: Includes a docker `config.json`
      optional: true
      mountPath: /kaniko/.docker
    - name: source
      description: source code storage
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: github-build
spec:
  serviceAccountName: cncamp-sa
  taskRef:
    name: github-build
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: storage-code
    - name: dockerconfig
      secret:
        secretName: docker-auth
