apiVersion: v1
kind: Pod
metadata: 
  name: test-pod
  namespace: default
  labels:
    app: his
  annotations:
    release: v1.0.0
spec:
  containers:
  - image: tomcat:8.5-jre8-alpine 
    imagePullPolicy: IfNotPresent
    name: test
    ports:
    - containerPort: 8080
      name: web-test
    resources:
      limits:
        cpu: 0.5
        memory: 1Gi
      requests:
        cpu: 0.1
        memory: 128Mi

      
