kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  namespace: devops
spec:
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteMany

