apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
  name: test
  namespace: monitor
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    component: grafana
  type: ClusterIP
