apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

patchesStrategicMerge:
  - hpa.yaml

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: backend
  path: op-env.yaml