{{- with .Values.core }}
{{- $fullName := printf "%s-%s" (include "jumpserver.fullname" $) "jms-init-db" }}
{{- $containerName := "jms-init-db" }}
{{- $image := printf "%s" (include "jumpserver.coreImage" $) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}
  labels:
    app.jumpserver.org/name: {{ $containerName }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        {{- toYaml .labels | nindent 8 }}
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml $.Values.global.imagePullSecrets }}
      {{- end }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $containerName }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ $image }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          command:
            - /bin/bash
            - "-c"
            - cd /opt/jumpserver && ./jms upgrade_db
          env:
            - name: SECRET_KEY
              value: "{{ .config.secretKey }}"
            - name: BOOTSTRAP_TOKEN
              value: "{{ .config.bootstrapToken }}"
              {{- end }}
            - name: DB_ENGINE
              value: {{ include "jumpserver.database.engine" . | quote }}
            - name: DB_HOST
              value: {{ include "jumpserver.database.host" . | quote }}
            - name: DB_PORT
              value: {{ include "jumpserver.database.port" . | quote }}
            - name: DB_USER
              value: {{ include "jumpserver.database.user" . | quote }}
            - name: DB_PASSWORD
              value: {{ include "jumpserver.database.password" . | quote }}
            - name: DB_NAME
              value: {{ include "jumpserver.database.database" . | quote }}
            - name: REDIS_HOST
              value: {{ include "jumpserver.redis.host" . | quote }}
            - name: REDIS_PORT
              value: {{ include "jumpserver.redis.port" . | quote }}
            - name: REDIS_PASSWORD
              value: {{ include "jumpserver.redis.password" . | quote }}
          {{- with .env }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
      restartPolicy: Never