{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jumpserver.serviceAccountName" . }}
  labels:
    {{- include "jumpserver.labels" . | nindent 4 }}
imagePullSecrets:
  {{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end -}}
