apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-clone-checking-out-a-branch
spec:
  pipelineRef:
    name: cat-branch-readme
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: storage-code
  params:
    - name: repo-url
      value: https://github.com/tektoncd/pipeline.git
    - name: branch-name
      value: release-v0.12.x
