apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: example-run
spec:
  taskRef:
    name: kaniko-build
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: storage-code
    - name: dockerconfig
      secret:
        secretName: regcred
  params:
    - name: IMAGE
      value: zheng11581/mall-admin
    - name: DOCKERFILE
      value: Dockerfile
