kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
  namespace: default
spec:
  selector:
    matchLabels:
       app: nfs-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: zheng11581/nfs-provisioner:v4.0.0
          volumeMounts:
            - name: nfs-provisioner
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: example.com/nfs
            - name: NFS_SERVER
              value: 192.168.110.72
            - name: NFS_PATH
              value: /glzt/nfs-provisioner
      volumes:
        - name: nfs-provisioner
          nfs:
            server: 192.168.110.72
            path: /glzt/nfs-provisioner

