apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
      default: goharbor.com/mall-swarm/mall-admin
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./mall-admin/Dockerfile
  steps:
    - name: sleep
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        sleep 600
    - name: build-image
      image: cncamp/executor
      workingDir: /workspace/source
      args:
        - "--dockerfile=${params.DOCKERFILE}"
        - "--context=/workspace/source"
        - "--destination=${params.IMAGE}"
  workspaces:
    - name: dockerconfig
      description: Includes a docker `config.json`
      optional: true
      mountPath: /kaniko/.docker
    - name: source
      description: source code storage
