apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
      default: goharbor.com/mall-swarm/mall-admin
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./mall-admin/Dockerfile
  steps:
    - name: build-image
      image: gcr.io/kaniko-project/executor:v1.5.1
      workingDir: /workspace/source
      args:
        - "--dockerfile=./mall-admin/Dockerfile"
        - "--context=./mall-admin"
        - "--destination=goharbor.com/mall-swarm/mall-admin:latest"
  workspaces:
    - name: dockerconfig
      description: Includes a docker `config.json`
      optional: true
      mountPath: /kaniko/.docker
    - name: source
      description: Holds the context and Dockerfile
