apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: example-run
spec:
  taskRef:
    name: kaniko
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: storage-code
    - name: dockerconfig
      secret:
        secretName: default-token-zm6dl
  params:
    - name: CONTEXT
      value: mall-admin
    - name: IMAGE
      value: goharbor.com/mall-swarm/mall-admin
