apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: example-run
spec:
  taskRef:
    name: kaniko-build
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: storage-code
  params:
    - name: IMAGE
      value: goharbor.com/mall-swarm/mall-admin
