apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv001"
  namespace: "devops"
  labels:
    app: localstore01
spec:
  accessModes: 
  - ReadWriteMany
  hostPath: 
    path: /data/pv
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  
