apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>

    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

    <servers>
    <!--配置私服认证信息-->
    <server>
    <id>public</id>
    <username>cicd</username>
    <password>cicd@GLZT.2020</password>
    </server>
    </servers>

    <mirrors>
    <mirror>
    <id>public</id>
    <mirrorOf>*</mirrorOf>
    <name>maven-public</name>
    <url>http://192.168.110.72:8081/repository/maven-public/</url>
    </mirror>
    </mirrors>

    <profiles>
    <profile>
    <id>glzt</id>
    <repositories>
    <repository>
    <id>public</id>
    <name>maven-public</name>
    <url>http://192.168.110.72:8081/repository/maven-public/</url>
    <layout>default</layout>
    <releases>
    <enabled>true</enabled>
    </releases>
    <snapshots>
    <enabled>true</enabled>
    <updatePolicy>always</updatePolicy>
    </snapshots>
    </repository>
    </repositories>
    </profile>

    </profiles>

    <activeProfiles>
    <activeProfile>glzt</activeProfile>
    </activeProfiles>
    </settings>
