apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIuaW8iOiB7CgkJCSJhdXRoIjogImVtaGxibWN4TVRVNE1UcDZhR1Z1WnpFeE5UZ3hRRVJ2WTJ0bGNnPT0iCgkJfSwKCQkiZ29oYXJib3IuY29tIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NllXUnRhVzVBUjB4YVZDNHlNREl3IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
