apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnb2hhcmJvci5jb20iOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2WVdSdGFXNUFSMHhhVkM0eU1ESXciCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJlbWhsYm1jeE1UVTRNVHA2YUdWdVp6RXhOVGd4UUVSdlkydGxjZz09IgoJCX0KCX0K # base64 encode ~/.docker/config.json
type: kubernetes.io/dockerconfigjson
