apiVersion: v1
kind: Secret
metadata:
  name: harbor
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnb2hhcmJvci5jb20iOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2WVdSdGFXNUFSMHhhVkM0eU1ESXciCgkJfQoJfQp9 # base64 encode ~/.docker/config.json
type: kubernetes.io/dockerconfigjson
