apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: example-run
spec:
  taskRef:
    name: kaniko
  workspaces:
    - name: source
      emptyDir: {}
    - name: dockerconfig
      secret:
        secretName: dockerhub
